version: '3.1'

services:
  yex-dev:
    container_name: yex-dev
    hostname: yex-dev
    build: .
    restart: always
    ports:
      -  8100:8100 # Ionic dev server port
      -  8090:8090 # Dev port 1
      -  8091:8091 # Dev port 2
      -  8092:8092 # Dev port 3
      -  8093:8093 # Dev port 4
      -  8094:8094 # Dev port 5
      -  8095:8095 # Dev port 6
    volumes:
        - ./workspace:/root/workspace
    priviledged: true