version: '3.9'

services:
  yex-dev:
    container_name: yex-dev
    hostname: yex-dev
    build: ./build
    image: yex-dev:latest
    restart: always
    environment:
      - "TZ:Europe/Berlin"
    ports:
      -  "10081:8100" # Ionic dev server port
      -  "10022:22"   # SSH Port
      -  "10090:8090" # Dev port 1
      -  "10091:8091" # Dev port 2
      -  "10092:8092" # Dev port 3
      -  "10093:8093" # Dev port 4
      -  "10094:8094" # Dev port 5
      -  "10095:8095" # Dev port 6
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock # docker socket so we can build images
        - ./workspace:/root/workspace # workspace mapping
        - ~/.ssh/:/root/.ssh/:ro # ssh keys of the host
        - /etc/shadow:/etc/shadow:ro # passwords of the host
        - ~/.docker/:/root/.docker # user host docker config
        - ~/.gitconfig/:/root/.gitconfig:ro # use host git config
        - /etc/ssh/:/etc/ssh:ro # map sshd config
        - ~/.p10k.zsh:/root/.p10k.zsh:ro # maintain consistent p10k style
        - ~/powerlevel10k:/root/powerlevel10k:ro # maintain consistent p10k style
        - ~/.zsh_history:/root/.zsh_history:rw # share zsh history
        - "/etc/timezone:/etc/timezone:ro" # set correct timezone 
        - "/etc/localtime:/etc/localtime:ro" # set correct time

